version: "3.8"
services:
  # server:
  #   build:
  #     context: "./server"
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${SERVER_PORT}:${SERVER_PORT}"
  #   volumes:
  #     - ./server:/server
  #   links:
  #     - db
  #   env_file:
  #     - .env

  db:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./cache:/data
