<<<<<<< HEAD
version: "3.8"
services:
  # server:
  #   build:
  #     context: "./server"
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${SERVER_PORT}:${SERVER_PORT}"
  #   volumes:
  #     - ./server:/server
  #   links:
  #     - db
  #   env_file:
  #     - .env

=======
version: '3.8'
services:
  server:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
     - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/server
    links:
      - db
    env_file:
      - .env
    
>>>>>>> 060e48e (initial commit)
  db:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env
<<<<<<< HEAD
=======

>>>>>>> 060e48e (initial commit)
